#pragma once

#include "internal/common.h"
#include "math/decompose_lu.h"
#include "math/decompose_qr.h"
// #include "math/decompose_svd.h"
#include "math/mat_func.h"
#include "math/quat_func.h"
#include "math/rect.h"
#include "math/transforms/orthographic.h"
#include "math/transforms/perspective.h"
#include "math/transforms/rotation_2d.h"
#include "math/transforms/rotation_3d.h"
#include "math/transforms/scale.h"
#include "math/transforms/shear.h"
#include "math/transforms/translation.h"
#include "math/transforms/view.h"
#include "math/vec_func.h"
